---
kind: pipeline
type: docker
name: build & deploy

steps:
- name: Build the app
  image: node:current-alpine3.15
  volumes:
  - name: app
    path: /dist
  commands:
  - npm ci
  - npm run build
  - echo OK
  - echo OK2